### ISSUE TITLE
Terminal not functioning

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#2]
<img width="1562" alt="Screen Shot 2020-03-15 at 5 52 35 PM" src="https://user-images.githubusercontent.com/43240374/76711383-ee503800-66e5-11ea-8928-2b12b28299d3.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
When you put in the `bundle exec jekyll serve` command, what happens?

**Comment by kyleellis14** [comment]
<img width="570" alt="Screen Shot 2020-03-15 at 7 50 35 PM" src="https://user-images.githubusercontent.com/43240374/76713329-3d9e6480-66f6-11ea-91c5-c217b266511d.png">



got it back to the working state to update however it now has an error that I can not seem to fix or figure out.

**Comment by thomasjbradley** [comment]
Commit & push, please.

**Comment by kyleellis14** [comment]
completed.

**Comment by thomasjbradley** [comment]
Have a look at the homepage’s code here:
https://github.com/kyleellis14/ecommerce-pattern-library/blob/master/index.html#L5

It refers to a pattern named `cards/banner` but your banner isn’t in the `cards` folder, it’s in the `banner` folder. So it should say `banner/banner`

**Comment by kyleellis14** [comment]
Working... Thank you!
