### ISSUE TITLE
Quizes

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#4]
Markdown manipulator and YAML yodler completed
<img width="1680" alt="Screen Shot 2020-03-23 at 1 12 47 PM" src="https://user-images.githubusercontent.com/43240374/77345772-7ef0ce80-6d0b-11ea-9c9c-9bad00881465.png">
<img width="1680" alt="Screen Shot 2020-03-23 at 1 30 47 PM" src="https://user-images.githubusercontent.com/43240374/77345828-8fa14480-6d0b-11ea-80e1-016a99cd12ae.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
:sparkles:
