### ISSUE TITLE
FInished building pages and leftovers 

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#5]
The only thing I haven't been able to accomplish is my button taking me to the shop page(aka products).

**Comment by kyleellis14** [comment]
button is linked and pushed now

**Comment by kyleellis14** [comment]
@thomasjbradley I forgot to tag you!

**Comment by thomasjbradley** [comment]
What did you add to your pattern library for “The leftovers”?

**Comment by kyleellis14** [comment]
I didn't add any additional pages to my pattern library however I added an extra button element for my card not sure if that does count or not?

**Comment by thomasjbradley** [comment]
Yep—that works.

**Comment by kyleellis14** [comment]
ok perfect thank you! and was anything wrong for my building pages?

**Comment by thomasjbradley** [comment]
Building pages was good. I thought I put the grade in for it but apparently not. It’s there now.

**Comment by kyleellis14** [comment]
Ok thank you!
i will close the issues the ones you marked
