### ISSUE TITLE
Finished Preparing product data

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#6]
<img width="1637" alt="Screen Shot 2020-03-24 at 12 30 45 PM" src="https://user-images.githubusercontent.com/43240374/77451739-765fcd00-6dcb-11ea-9836-efa91c46f1c9.png">
@thomasjbradley
<img width="1637" alt="Screen Shot 2020-03-24 at 12 30 53 PM" src="https://user-images.githubusercontent.com/43240374/77451788-837cbc00-6dcb-11ea-8c11-99c9a296b3b5.png">
<img width="1637" alt="Screen Shot 2020-03-24 at 12 31 02 PM" src="https://user-images.githubusercontent.com/43240374/77451812-8e375100-6dcb-11ea-9128-e03d16381f67.png">
<img width="1637" alt="Screen Shot 2020-03-24 at 12 31 31 PM" src="https://user-images.githubusercontent.com/43240374/77451848-98594f80-6dcb-11ea-9918-eb8ac5805658.png">

**Comment by thomasjbradley** [comment]
✨
