### ISSUE TITLE
Finished Home Page template 

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#8]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Your homepage only has a single banner on it? Not other content?

**Comment by kyleellis14** [comment]
Correct as a landing page with a call to action. no other information was needed for mine? Do you have suggestions as to what I could add to it?

**Comment by thomasjbradley** [comment]
Featured products?
Sale products?
Company introduction/about us?
Email newsletter?

There’s nothing on the homepage to draw me into clicking on other things.

**Comment by kyleellis14** [comment]
ok, I will figure out something for the home page.

**Comment by kyleellis14** [comment]
I have created an Email Newsletter sign up page on my Home Page. That completes my home page.

**Comment by kyleellis14** [comment]
I also added a favicon I'm not sure if that was needed?

**Comment by thomasjbradley** [comment]
👍
